export const classificationCategories = [
  {
    classification: "Analgesia y Antiinflamatorios",
    categories: [
      "Analgésicos",
      "Antiinflamatorios",
      "Antipiréticos",
      "Anestésicos locales",
      "Antirreumáticos",
      "Otros",
    ],
  },
  {
    classification: "Antimicrobianos",
    categories: [
      "Antibióticos",
      "Antivirales",
      "Antifúngicos",
      "Antiparasitarios",
      "Antisépticos",
      "Otros",
    ],
  },
  {
    classification: "Sistema Gastrointestinal",
    categories: [
      "Antidiarreicos",
      "Antieméticos",
      "Laxantes",
      "Protectores gástricos",
      "Reguladores intestinales",
      "Antiácidos",
      "Antiespasmódicos",
      "Antiflatulentos",
      "Otros",
    ],
  },
  {
    classification: "Sistema Respiratorio",
    categories: [
      "Antitusivos",
      "Expectorantes",
      "Descongestionantes",
      "Broncodilatadores",
      "Mucolíticos",
      "Antiasmáticos",
      "Alivio del sistema respiratorio",
      "Antihistamínicos",
      "Corticosteroides Inhalados",
      "Antagonistas de Leucotrienos",
      "Agentes para la Tos",
      "Otros",
    ],
  },
  {
    classification: "Cuidado Cardiovascular",
    categories: [
      "Cardiotónicos",
      "Antihipertensivos",
      "Antidiabéticos",
      "Anticoagulantes",
      "Antiarrítmicos",
      "Bienestar cardiovascular",
      "Diuréticos",
      "Vasodilatadores",
      "Estatinas",
      "Antianginosos",
      "Antiagregantes plaquetarios",
      "Betabloqueadores",
      "Otros",
    ],
  },
  {
    classification: "Salud Mental",
    categories: [
      "Antipsicóticos",
      "Psicoestimulantes",
      "Ansiolíticos",
      "Antidepresivos",
      "Neurolépticos",
      "Antiepilépticos",
      "Estabilizadores del ánimo",
      "Tratamientos para trastornos del sueño",
      "Antimaníacos",
      "Otros",
    ],
  },
  {
    classification: "Cuidado Dermatológico",
    categories: [
      "Antiacné",
      "Antipiojos",
      "Cicatrizantes",
      "Hidratantes",
      "Antioxidantes",
      "Cuidado de la piel",
      "Cuidado del cabello",
      "Cuidado solar",
      "Exfoliantes",
      "Despigmentantes",
      "Antiarrugas",
      "Antiirritantes",
      "Limpiadores faciales",
      "Tratamiento de psoriasis",
      "Tratamiento de eczema",
      "Protectores labiales",
      "Tratamiento de dermatitis",
      "Cremas para pieles sensibles",
      "Tratamiento de verrugas",
      "Tratamiento de hongos en la piel",
      "Productos para contorno de ojos",
      "Aceites para la piel",
      "Otros",
    ],
  },
  {
    classification: "Cuidado Personal",
    categories: [
      "Repelentes",
      "Cuidado auditivo",
      "Cuidado bucal",
      "Cuidado ocular",
      "Cuidado nasal",
      "Higiene corporal",
      "Desodorantes y antitranspirantes",
      "Protección solar",
      "Otros",
    ],
  },
  {
    classification: "Sistema Nervioso Central",
    categories: [
      "Sedantes",
      "Inmunosupresores",
      "Neuroprotectores",
      "Anticonvulsivos",
      "Antiparkinsonianos",
      "Otros",
    ],
  },
  {
    classification: "Salud Femenina",
    categories: [
      "Salud Reproductiva",
      "Anticoncepción",
      "Menopausia y Perimenopausia",
      "Higiene Femenina",
      "Enfermedades Ginecológicas",
      "Suplementos prenatales",
      "Accesorios para la Salud Femenina",
      "Productos Postparto",
      "Pruebas de embarazo y ovulación",
      "Otros",
    ],
  },
  {
    classification: "Salud sexual",
    categories: [
      "Anticonceptivos",
      "Preservativos",
      "Lubricantes íntimos",
      "Estimulantes sexuales",
      "Suplementos para la fertilidad",
      "Otros",
    ],
  },
  {
    classification: "Suplementos y Vitaminas",
    categories: [
      "Multivitamínicos",
      "Minerales",
      "Ácidos grasos esenciales",
      "Proteínas y Aminoácidos",
      "Suplementos Deportivos",
      "Energizantes naturales",
      "Complejos vitamínicos",
      "Ácidos Grasos y Omega-3",
      "Otros",
    ],
  },
  {
    classification: "Otros Productos Farmacéuticos",
    categories: [
      "Medicamentos Específicos",
      "Suplementos Adicionales",
      "Productos para el Cuidado Especializado",
      "Productos Naturales",
      "Productos para la Salud General",
      "Otros",
    ],
  },
];
